AWSTemplateFormatVersion: 2010-09-09
Description: |
  This temp launches an ec2 instance with apache server.
Resources:
  PrjCFN101Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - !Ref CFNSecGroup
      Tags:
        - Key: Name
          Value: project101
      UserData: IyEgL2Jpbi9iYXNoCnl1bSB1cGRhdGUgLXkKeXVtIGluc3RhbGwgLXkgaHR0cGQKREFURV9USU1FPWBkYXRlYAplY2hvICI8aHRtbD4KPGhlYWQ+Cjx0aXRsZT4gTXkgRmlyc3QgV2ViIFNlcnZlcjwvdGl0bGU+CjwvaGVhZD4KPGJvZHk+CjxoMT5IZWxsbyB0byBFdmVyeW9uZSBmcm9tIE15IEZpcnN0IFdlYiBTZXJ2ZXI8L2gxPgo8cD5UaGlzIGluc3RhbmNlIGlzIGNyZWF0ZWQgYXQgPGI+JERBVEVfVElNRTwvYj48L3A+CjwvYm9keT4KPC9odG1sPiIgPiAvdmFyL3d3dy9odG1sL2luZGV4Lmh0bWwKc3lzdGVtY3RsIHN0YXJ0IGh0dHBkCnN5c3RlbWN0bCBlbmFibGUgaHR0cGQ=
  
  CFNSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH for CFN Instance # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

